services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE:-rabbitmq:4.3.4-management}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq-learning}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-study}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-study123}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      # AMQP
      # Spring Boot 真正连接 RabbitMQ 使用的端口
      - "${RABBITMQ_PORT:-5673}:5672"
      # RabbitMQ Management 管理页面
      - "${RABBITMQ_MANAGEMENT_PORT:-15673}:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network
  mysql:
    image: mysql:8.0
    container_name: mysql_learning
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: rabbitmq_demo
      MYSQL_USER: rabbitmq
      MYSQL_PASSWORD: rabbitmq123
    ports:
      - "3307:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
networks:
  rabbitmq-network:
    driver: bridge