services:
  rabbitmq:
    # RabbitMQ 镜像版本
    image: ${RABBITMQ_IMAGE:-rabbitmq:4.3.4-management}
    # 容器名字
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq-learning}
    restart: unless-stopped
    environment:
      # RabbitMQ 登录账号
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-study}
      # RabbitMQ 登录密码
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-study123}
      # Virtual Host
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      # AMQP
      # Spring Boot 真正连接 RabbitMQ 使用的端口
      - "${RABBITMQ_PORT:-5673}:5672"
      # RabbitMQ Management 管理页面
      - "${RABBITMQ_MANAGEMENT_PORT:-15673}:15672"
    volumes:
      # RabbitMQ 数据持久化
      # 即使容器删除后重新创建，
      # Exchange / Queue 等数据仍可以保留
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network
networks:
  rabbitmq-network:
    driver: bridge