server:
  # Spring Boot Web 服务端口
  port: 8080

spring:
  application:
    # 应用名称，后续查看日志和监控时会用到
    name: rabbitmq-demo

  datasource:
    # H2 内存数据库；应用关闭后数据清空
    url: jdbc:h2:mem:rabbitmq_demo
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      # 开启 H2 网页管理后台
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      # 学习阶段自动创建和更新数据库表
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    # RabbitMQ 运行在本机 Docker 中
    host: localhost
    # Java 客户端连接 RabbitMQ 使用的 AMQP 端口
    port: 5673
    username: study
    password: study123
    # 开启 Publisher Confirm
    publisher-confirm-type: correlated
    # 开启无法路由消息的 Return 回调
    publisher-returns: true
    template:
      # 消息没有匹配任何队列时，将消息退回生产者
      mandatory: true
    listener:
      simple:
        # 三次重试之后还是无法正常消费，那就重新入队，一直放在queue上面；
        # acknowledge-mode: auto
        # 三次重试后还是不行自动丢弃消息
        acknowledge-mode: auto
        # 每个消费者最多同时持有 20 条未确认消息
        prefetch: 20
        # 初始消费者线程数
        concurrency: 1
        # 高峰期最大消费者线程数
        max-concurrency: 8
        # 最终消费失败后不要重新塞回原队列
        default-requeue-rejected: false

        # =========================
        # Consumer 消费重试配置
        # =========================
        retry:
          # 开启消费者重试机制
          enabled: true
          # 最多尝试 3 次
          # 注意：包含第一次执行。第一次 + 重试2次 = 总共3次；
          max-attempts: 3
          # 第一次失败后，等待 1 秒
          initial-interval: 1000ms
          # 下一次等待时间 = 上一次 × 2
          multiplier: 2
          # 最长等待不超过 5 秒
          max-interval: 5000ms


management:
  endpoints:
    web:
      exposure:
        # 学习阶段开放健康检查和指标端点
        include: health,info,metrics